apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app1: backend12344
    spec:
      containers:
      - name: backend
        image: jagannathgawali7/elaundry-backend:dev-24-08-2024
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: rootpassword
        - name: DB_NAME
          value: mydatabase
