apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-job
  namespace: ns1
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:5.7
        command:
        - /bin/sh
        - -c
        - |
          mysql -h mysql -u myuser -pmypassword book <<EOF
          CREATE TABLE books (
            id INT AUTO_INCREMENT PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            author VARCHAR(255) NOT NULL,
            published_date DATE
          );

          INSERT INTO books (title, author, published_date) VALUES
          ('The Great Gatsby', 'F. Scott Fitzgerald', '1925-04-10'),
          ('To Kill a Mockingbird', 'Harper Lee', '1960-07-11'),
          ('1984', 'George Orwell', '1949-06-08');

          EOF
      restartPolicy: Never
