apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 9095
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/api/prom/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_name']
            target_label: 'pod_name'
          - source_labels: ['__meta_kubernetes_namespace']
            target_label: 'namespace'
          - source_labels: ['__meta_kubernetes_pod_container_name']
            target_label: 'container_name'
