apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    app: {{ .Values.backend.deployment.appLabel }}
spec:
  selector:
    app: {{ .Values.backend.service.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      name: node-backend-port
  type: {{ .Values.backend.service.type }}
