apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.mysql.initJob.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.mysql.initJob.containerName }}
        image: {{ .Values.mysql.initJob.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.env.rootPassword }}
        command: ["sh", "-c"]
        args:
        - |
          mysql -h {{ .Values.mysql.service.name }} -u root -p$MYSQL_ROOT_PASSWORD -e "
          USE {{ .Values.mysql.env.database }};
          CREATE TABLE IF NOT EXISTS items (
              id INT AUTO_INCREMENT PRIMARY KEY,
              name VARCHAR(255) NOT NULL,
              description TEXT,
              price DECIMAL(10, 2)
          );
          INSERT IGNORE INTO items (name, description, price) VALUES
          ('T-Shirt', 'Comfortable cotton t-shirt', 19.99),
          ('Jeans', 'Stylish blue jeans', 39.99);
          "
      restartPolicy: Never
  backoffLimit: 4
