apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.deployment.appLabel }}
    spec:
      containers:
      - name: {{ .Values.mysql.deployment.containerName }}
        image: {{ .Values.mysql.deployment.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.env.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.env.database }}
        ports:
        - containerPort: {{ .Values.mysql.deployment.containerPort }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.targetPort }}
  selector:
    app: {{ .Values.mysql.service.appLabel }}
  type: ClusterIP
