# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ .Values.mysql.pv.name }}
# spec:
#   capacity:
#     storage: {{ .Values.mysql.pv.capacity }}
#   accessModes:
#     - {{ .Values.mysql.pv.accessMode }}
#   hostPath:
#     path: {{ .Values.mysql.pv.path }}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Values.mysql.pvc.name }}
# spec:
#   resources:
#     requests:
#       storage: {{ .Values.mysql.pvc.storageRequest }}
#   accessModes:
#     - {{ .Values.mysql.pvc.accessMode }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.pvc.name }}
spec:
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.storageRequest }}
  accessModes:
    - {{ .Values.mysql.pvc.accessMode }}
  storageClassName: {{ .Values.storageClassName }}  # Specify storage class here
